### ISSUE TITLE
Tests with LXC

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/harden.sh#43]
Maybe use Ansible's [lxc_container module](https://docs.ansible.com/ansible/latest/modules/lxc_container_module.html). Something like:

* Deploy fresh host (Debian or Slackware)
* Take snapshot
* Install Lynis
* Take Lynis baseline score
* Run hardenings
* Run Lynis again
* Take the hardened score
* Revert snapshot?
* Make conclusions
* Check modified files with SHA-2 etc.

## TODO

* [ ] Look into [distrobuilder](https://github.com/lxc/distrobuilder)
* [ ] Use [overlayfs](https://stgraber.org/2013/12/27/lxc-1-0-container-storage/) to create a temp container for the tests
* [ ] Use the download template, so we can have Slackware container in Debian (`pkgtools` missing in Debian)
  * <https://blog.ubuntu.com/2016/04/01/lxd-2-0-image-management-512>

## Lynis tests to disable

* FILE-6310 (Checking /tmp, /home and /var directory)

**Comment by pyllyukko** [comment]
[![asciicast](https://asciinema.org/a/Hq1esBXvDZz95MHLnPxPyEAor.png)](https://asciinema.org/a/Hq1esBXvDZz95MHLnPxPyEAor)

**Comment by pyllyukko** [comment]
Trouble ahead. Currently "Create the containers" task fails with:

```
AttributeError: module 'lxc' has no attribute 'Container'
```

**Comment by pyllyukko** [comment]
I'm ditching this. Initial tests with Molecule and Docker are now implemented. `lxc.yml` needs to be removed at some point.
